### ISSUE TITLE
Support all the ANSI escape codes for styling

### ISSUE THREAD

**Issue by IonicaBizau** [IonicaBizau/anser#1]
<sub>Ported issue from https://github.com/IonicaBizau/ansi-to-json/issues/2</sub>

* [x] `[1m`/bold  	Set "bright" attribute
* [x] `[2m`/dim		Set "dim" attribute
* [x] `[4m`/smul 	Set "underscore" (underlined text) attribute
* [x] `[5m`/blink 	Set "blink" attribute
* [x] `[7m`/rev    	Set "reverse" attribute
* [x] `[8m`/invis 	Set "hidden" attribute

[Code ref](http://wiki.bash-hackers.org/scripting/terminalcodes)

**Comment by IonicaBizau** [comment]
@rgbkrk Support for underline and blink text was added by @lgeiger. /cc #7 :rocket:

**Comment by IonicaBizau** [comment]
It's amazing to see how simple it was to add that.

@lgeiger If you like to add the others, that would be great! Just few more conditions for the others (1, 2, 7, 8). `bright` support is already there, but not added as *decoration*.

**Comment by IonicaBizau** [comment]
@rgbkrk I have a work-in-progress in the `new-version` branch. I have to fix the tests and then I will 🚢 it. 😁

**Comment by rgbkrk** [comment]
Awesome!

**Comment by IonicaBizau** [comment]
🚢 **`1.1.0`** 🎉
