### ISSUE TITLE
Typescript - Definetly Typed

### ISSUE THREAD

**Issue by clouless** [IonicaBizau/anser#31]
Hi @IonicaBizau 
I hope you are doing well 😄 

I just begun coding an Angular App with Typescript,
and would like to provide Typings for Anser.

I will create a PR for DefinetlyTyped and maybe you can also review/contribute.
Howto:
https://github.com/DefinitelyTyped/DefinitelyTyped

I will report back here once I have something working

cheers

**Comment by IonicaBizau** [comment]
Cool! :+1: Just reference it here.

**Comment by clouless** [comment]
Ok i just read a little, and we could also directly provide types from this repo.

See: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

This would be my favorite.

**Comment by IonicaBizau** [comment]
Thanks again! 👍
