### ISSUE TITLE
Broaden support for more ansi styles

### ISSUE THREAD

**Issue by satazor** [IonicaBizau/anser#34]
Only a subset of all ansi styles are being supported, for instance, grey, bold, striketrough are missing.

The parser could be improved to deal with the ansi-styles present here: https://github.com/chalk/ansi-styles/blob/master/index.js#L21, probably by using that module itself.

Thoughts?

**Comment by IonicaBizau** [comment]
@satazor Thanks for this! Some examples of input and output would help.

Contributions are also welcome! Otherwise, I will do it when I get a bit of free time. 😁

**Comment by satazor** [comment]
No problemo! I'm afraid I don't have the time for this, anyway let's see who picks this up first :)
