### ISSUE TITLE
Bogus typings

### ISSUE THREAD

**Issue by marechal-p** [IonicaBizau/anser#52]
https://github.com/IonicaBizau/anser/commit/06527e47be0efedba4c51657197056bcbb7b872f#diff-0e3ac3694919aca1db302bc3ebe669f2R34

`export default` should be `export = `, according to the way your package is actually behaving.

`export default` makes TypeScript think that there is a `default` property like `exports.default = `, which is not the case.

**Comment by cdeutsch** [comment]
Related to #50 which recently changed the typings.

**Comment by IonicaBizau** [comment]
Feel free to contribute... I am not very good in how typings work.

**Comment by RDIL** [comment]
@IonicaBizau I opened #60 to fix this.
