### ISSUE TITLE
use_classes returns wrong names for JSON chunks

### ISSUE THREAD

**Issue by travigd** [IonicaBizau/anser#53]
Found this initially https://github.com/nteract/nteract/issues/4816. This might be as intended, but as I think about it more, I think its an issue here rather than in `ansi-to-react`.

tl;dr:

```js
Anser.ansiToJson("\u001b[40mhello\u001b[0m", {use_classes: true}
```
yields
```js
[
  {
    "content": "",
    "fg": null,
    "bg": null,
    "fg_truecolor": null,
    "bg_truecolor": null,
    "clearLine": false,
    "decoration": null,
    "was_processed": false
  },
  {
    "content": "hello",
    "fg": null,
    "bg": "ansi-black",
    "fg_truecolor": null,
    "bg_truecolor": null,
    "clearLine": false,
    "decoration": null,
    "was_processed": true
  },
  {
    "content": "",
    "fg": null,
    "bg": null,
    "fg_truecolor": null,
    "bg_truecolor": null,
    "clearLine": false,
    "decoration": null,
    "was_processed": false
  }
]
```
where the colors are given as `ansi-black` instead of `ansi-black-fg`.

The HTML output is
```html
<span class="ansi-black-bg">hello</span>
```

**Comment by ktunkiewicz** [comment]
The `[40` is a black *background* colour code, not a black foreground (https://en.wikipedia.org/wiki/ANSI_escape_code#SGR).
And in the JSON object you see the `ansi-black` value in the `bg` property. Seems all fine to me.

**Comment by IonicaBizau** [comment]
@travigd Does @ktunkiewicz's comment help you?

**Comment by travigd** [comment]
Yep, closing. :)
